name: "Trigger DAG Action"
description: "Trigger an Airflow DAG hosted on GCP"
author: "Explorium DevOps Team"
branding:
  icon: activity
  color: blue
inputs:
  payload:
    description: 'JSON Payload'
    required: false
    default: '"config": {"run_type":"PR"}'
  dag_run_id:
    description: 'custom dag run id'
    required: true
    default: ''
  client_id:
    description: 'gcp client id'
    required: true
    default: ''
  webserver_id:
    description: 'webserver id'
    required: true
    default: ''         
  dag_name:
    description: 'dag name'
    required: true
    default: ''
  google_application_credentials: 
    description: 'location of gcp credentials'
    required: true
    default: './gcp_creds.json'     
outputs:
  result:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"