name: "Trigger DAG Action"
description: "Trigger an Airflow DAG hosted on GCP"
author: "Explorium DevOps Team"
inputs:
  entity_client_version:
    description: 'entity client version'
    required: true
    default: 'latest'
  dag_run_id:
    description: 'custom dag run id'
    required: true
    default: ''
  client_id:
    description: 'gcp client id'
    required: true
    default: ''
  compare_threshold:
    description: 'compare threshold'
    required: true
    default: ''
  send_slack_on_errors:
    description: 'send slack on errors'
    required: false
    default: 'true'
  webserver_id:
    description: 'webserver id'
    required: true
    default: ''         
  run_type:
    description: 'run type'
    required: true
    default: ''     
  dag_name:
    description: 'dag name'
    required: true
    default: ''
  google_application_credentials: 
    description: 'location of gcp credentials'
    required: true
    default: './gcp_creds.json'     
outputs:
  result:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"